# Generated by Django 5.2.8 on 2025-11-11 12:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Customer's first name", max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="Customer's last name", max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(help_text="Customer's phone number", max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('address', models.TextField(help_text="Customer's full address", max_length=200, verbose_name='Address')),
                ('city', models.CharField(help_text="Customer's city", max_length=50, verbose_name='City')),
                ('country', models.CharField(default='Israel', help_text="Customer's country", max_length=50, verbose_name='Country')),
                ('company_name', models.CharField(blank=True, help_text="Customer's company (optional)", max_length=100, null=True, verbose_name='Company Name')),
                ('job_title', models.CharField(blank=True, help_text="Customer's job title (optional)", max_length=100, null=True, verbose_name='Job Title')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('blocked', 'Blocked')], default='active', help_text="Customer's current status", max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the customer', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(help_text='User who created this customer record', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
